---
  - name: restart mysql
    service:
      name: mysql
      state: restarted
    become: true

  - name: restart filebeat
    service:
      name: filebeat
      state: restarted
    become: true
