- hosts: web
  roles:
    - web
    - wordpress
- hosts: db
  roles:
    - { role: db, tags: ["db"] }
- hosts: monitor
  roles:
    - { role: grafana, tags: ["monitor"] }
    - { role: grafana-nginx, tags: ["monitor"] }
    - { role: prometheus, tags: ["monitor"] }
- hosts: elk
  roles:
    - { role: elk, tags: ["elk"] }
